---
abstract: 'Processing Wikidata Query Service SPARQL result.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  File::Object: 0
  JSON::XS: 0
  Perl6::Slurp: 0
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WQS-SPARQL-Result
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::Utils: 0.03
  Error::Pure: 0.15
  URI: 0
  perl: 5.6.2
resources:
  bugtracker: https://github.com/michal-josef-spacek/WQS-SPARQL-Result/issues
  homepage: https://github.com/michal-josef-spacek/WQS-SPARQL-Result
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/WQS-SPARQL-Result
version: '0.02'
